name: Makefile CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-codeql: true
        remove-docker-images: true
        root-reserve-mb: 40960
        # temp-reserve-mb: 10240

    - uses: actions/checkout@v3
    
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3
    - name: Install xmllint
      run: sudo apt-get install -y qemu-user-static qemu-utils


    - name: Install packer-builder-arm plugin and move to builder folder
      run: |
          git clone --depth 1 https://github.com/mkaczanowski/packer-builder-arm
          cd packer-builder-arm
          go mod download
          go build
          mv packer-builder-arm /home/runner/work/pwnagotchi-bookworm/pwnagotchi-bookworm/builder
          
    - name: Run make
      run: make

    - name: Run df
      run: |
          # Allow subsequent commands to run even if packer fails
          set +e
          
          # Run df
          df -h

          # Revert to default behavior (exit on error)
          set -e
      
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: pwnagotchi-raspios-lite.iso
    #     path: pwnagotchi-raspios-lite-**.**.**.**

#     - name: Image
#       run: make image -e PWN_HOSTNAME=pwnagotchi PWN_VERSION=0.0.1

    # - name: Release
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: pwnagotchi-raspios-lite
